services:
  db:
    image: postgres:14
    container_name: acalogos-postgres
    environment:
      POSTGRES_DB: bd_acalogos
      POSTGRES_USER: Roberto
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - acalogos_pgdata:/var/lib/postgresql/data

volumes:
  acalogos_pgdata: